@extends('layouts.app')
@section('content')
<div class="container">
    <h1 style="text-align: center">HISTORIA</h1>
    <p style="text-align: justify">
        EL TRANSPORTE SIEMPRE HA JUGADO UN ROL IMPORTANTE COMO MEDIO ARTICULADOR DE LA SOCIEDAD. EL DESARROLLO DE LA ECONOMÍA EN GENERAL, GIRA EN TORNO A LA MOVILIDAD DE PERSONAS Y BIENES FÍSICOS, ADEMÁS LA ESPECIALIZACIÓN ECONÓMICA SE HA POTENCIADO GRACIAS AL TRANSPORTE. EXISTE EVIDENCIA SOBRE EL EFECTO DE LA PROVISIÓN DE SERVICIOS DE TRANSPORTE, SOBRE LA REDUCCIÓN DE LA POBREZA EN ALGUNAS REGIONES DEL MUNDO.
EN LAS ÚLTIMAS DÉCADAS, LA EXPANSIÓN DEMOGRÁFICA, EN LAS CIUDADES DEL PAÍS, HA GENERADO UN INCREMENTO SUSTANCIAL EN LA DEMANDA POR SERVICIOS BÁSICOS, ENTRE LOS QUE SE INCLUYE EL TRANSPORTE DE PASAJEROS. ESTE CRECIMIENTO, NO FUE ACOMPAÑADO POR UNA PLANIFICACIÓN, EN LO REFERIDO A PARQUE AUTOMOTOR, NI A INFRAESTRUCTURA VIAL.
EL CRECIMIENTO POBLACIONAL EN LA CIUDAD DE ORURO, FUE ACELERADO ENTRE 1980-1990, PROPICIADO POR FACTORES COMO LA RELOCALIZACIÓN DE LAS MINAS Y EL CRECIMIENTO VEGETATIVO NATURAL. EN ESTA ETAPA, EL SISTEMA DE TRANSPORTE, TAMBIÉN CAMBIA, AL SUSTITUIRSE EL PARQUE AUTOMOTOR PRINCIPALMENTE CONFORMADO POR BUSES, POR UNIDADES DE MENOR CAPACIDAD. LOS HITOS IDENTIFICADOS EN RELACIÓN AL SISTEMA DE TRANSPORTE, PRESENTA LAS CARACTERÍSTICAS ADELANTE DESCRITAS.
    </p>
</div>
@endsection
