@extends('layouts.app')
@section('content')
<div class="container">
    <h1 style="text-align: center">MISIÓN</h1>
    <p style="text-align: justify">
        PROVEER A NUESTRA CIUDADANÍA LA APLICACIÓN WEB QUE IMPULSEN EL DESARROLLO COMPETITIVO Y PRODUCTIVO Y EFECTIVO PROPORCIONANDO, LA INFORMACIÓN NECESARIA PARA QUE PUEDAN ACCEDER Y VER LAS VENTAJAS DE LA PÁGINA WEB PARA PARADAS PROVINCIALES Y ASÍ SATISFACER LAS NECESIDADES DE NUESTRA CIUDADANÍA.
    </p>
</div>
@endsection
