@extends('layouts.app')
@section('content')
<div class="container">
    <h1 style="text-align: center">VISIÓN</h1>
    <p style="text-align: justify">
        NUESTRA APLICACIÓN FACILITARA EN EL DESARROLLO Y DESEMPEÑO DE NUESTRA CIUDAD YA QUE CON ELLA PODRÁN LLEGAR A UNA PARADA DE SALIDAS PROVINCIALES, CON UNA UBICACIÓN EN TIEMPO REAL YA QUE AHORA EXISTE LA TECNOLOGÍA INTERNET CELULARES, TABLET Y TAMBIÉN AYUDARA A LA CIUDAD EN LOS LUGARES TURÍSTICOS PORQUE EN LA ACTUALIDAD EXISTEN PROVINCIAS CON TURISMO.
    </p>
</div>
@endsection
